INSERT INTO style (id, style) VALUES (1, 'Clásica');
INSERT INTO style (id, style) VALUES (2, 'Blues');
INSERT INTO style (id, style) VALUES (3, 'Jazz');
INSERT INTO style (id, style) VALUES (4, 'Soul');
INSERT INTO style (id, style) VALUES (5, 'Rock and Roll');
INSERT INTO style (id, style) VALUES (6, 'Metal');
INSERT INTO style (id, style) VALUES (7, 'Punk');
INSERT INTO style (id, style) VALUES (8, 'Grunge');
INSERT INTO style (id, style) VALUES (9, 'Disco');
INSERT INTO style (id, style) VALUES (10, 'Pop');